# Generated by Django 6.0.2 on 2026-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('CUMULARE', 'Cumulare'), ('AREST_PREVENTIV', 'Arest preventiv'), ('NECLARITATI', 'Neclarități'), ('SOLICITARE_HOTARIRI', 'Solicitare hotărîri')], max_length=20),
        ),
    ]
