# Generated by Django 5.0.1 on 2026-02-11 08:03

import django.core.validators
import petitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='petition',
            new_name='petitions_p_registr_e0771f_idx',
            old_name='petitions_p_registr_7c7b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='petition',
            new_name='petitions_p_status_a80a91_idx',
            old_name='petitions_p_status_e93d7d_idx',
        ),
        migrations.RenameIndex(
            model_name='petition',
            new_name='petitions_p_petitio_451d84_idx',
            old_name='petitions_p_petitio_da9d5c_idx',
        ),
        migrations.RenameIndex(
            model_name='petition',
            new_name='petitions_p_object__bd2968_idx',
            old_name='petitions_p_object__7cfedb_idx',
        ),
        migrations.AlterField(
            model_name='petitionattachment',
            name='file',
            field=models.FileField(upload_to=petitions.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fișier'),
        ),
    ]
