# Generated by Django 5.0.1 on 2026-02-11 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_rename_petitions_p_registr_7c7b5e_idx_petitions_p_registr_e0771f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='detention_sector',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sector 1'), (2, 'Sector 2'), (3, 'Sector 3'), (4, 'Sector 4'), (5, 'Sector 5'), (6, 'Sector 6'), (7, 'Sector 7'), (8, 'Sector 8'), (9, 'Sector 9'), (10, 'Sector 10'), (11, 'Sector 11'), (12, 'Sector 12')], default=1, verbose_name='Sector detenție'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['detention_sector'], name='petitions_p_detenti_d19297_idx'),
        ),
    ]
