# Generated by Django 5.0.1 on 2026-02-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_427e4b_idx',
            old_name='notificatio_user_id_8c9c5e_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_type_ea918f_idx',
            old_name='notificatio_type_e60c9e_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_46ad24_idx',
            old_name='notificatio_created_bc28c9_idx',
        ),
    ]
