# Generated by Django 5.0.1 on 2026-02-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_actor_i_17b775_idx',
            old_name='audit_audit_actor_i_8defa1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_86e815_idx',
            old_name='audit_audit_action_e97c80_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_entity__9535bf_idx',
            old_name='audit_audit_entity__4c1c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_audit_created_9f46ae_idx',
        ),
    ]
