# Generated by Django 5.0.1 on 2026-02-05 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceReduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_article', models.CharField(max_length=50, verbose_name='Articol legal')),
                ('reduction_years', models.PositiveSmallIntegerField(default=0, verbose_name='Ani reduși')),
                ('reduction_months', models.PositiveSmallIntegerField(default=0, verbose_name='Luni reduse')),
                ('reduction_days', models.PositiveSmallIntegerField(default=0, verbose_name='Zile reduse')),
                ('applied_date', models.DateField(verbose_name='Data aplicării')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reductions', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='sentences.sentence', verbose_name='Sentință')),
            ],
            options={
                'verbose_name': 'Reducere pedeapsă',
                'verbose_name_plural': 'Reduceri pedeapsă',
                'ordering': ['-applied_date', '-created_at'],
            },
        ),
    ]
