# Generated by Django 5.0.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0004_change_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZPM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Luna')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Anul')),
                ('days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Zile lucrate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zpm_entries', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zpm_entries', to='sentences.sentence', verbose_name='Sentință')),
            ],
            options={
                'verbose_name': 'ZPM',
                'verbose_name_plural': 'ZPM',
                'ordering': ['-year', '-month'],
                'unique_together': {('sentence', 'month', 'year')},
            },
        ),
    ]
