# Generated by Django 5.0.1 on 2026-02-05 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convictedperson',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data internării'),
        ),
        migrations.AlterField(
            model_name='convictedperson',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNP-ul trebuie să conțină exact 13 cifre.', regex='^\\d{13}$')], verbose_name='CNP'),
        ),
        migrations.AlterField(
            model_name='convictedperson',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data nașterii'),
        ),
    ]
