# Generated by Django 5.0.1 on 2026-02-05 17:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvictedPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nume')),
                ('cnp', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CNP-ul trebuie să conțină exact 13 cifre.', regex='^\\d{13}$')], verbose_name='CNP')),
                ('date_of_birth', models.DateField(verbose_name='Data nașterii')),
                ('admission_date', models.DateField(verbose_name='Data internării')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
            ],
            options={
                'verbose_name': 'Persoană condamnată',
                'verbose_name_plural': 'Persoane condamnate',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['cnp'], name='persons_con_cnp_5aa295_idx'), models.Index(fields=['last_name', 'first_name'], name='persons_con_last_na_e58bce_idx'), models.Index(fields=['admission_date'], name='persons_con_admissi_8de7d2_idx')],
            },
        ),
    ]
