# Generated by Django 5.0.1 on 2026-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_convictedperson_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convictedperson',
            name='mai_notification',
            field=models.BooleanField(default=False, verbose_name='Înștiințare MAI'),
        ),
    ]
