# Generated by Django 5.0.1 on 2026-02-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('CUMULARE', 'Cumulare'), ('AREST_PREVENTIV', 'Arest preventiv'), ('NECLARITATI', 'Neclarități')], max_length=20),
        ),
    ]
