# Generated by Django 5.0.1 on 2026-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('email_from', models.EmailField(blank=True, default='', max_length=254)),
                ('email_to', models.TextField(blank=True, default='', help_text='Adrese email separate prin virgula')),
                ('enabled', models.BooleanField(default=False)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Configurare Email Monitor',
                'verbose_name_plural': 'Configurare Email Monitor',
            },
        ),
    ]
