# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_audit_audit_actor_i_8defa1_idx_audit_audit_actor_i_17b775_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('create', 'Creare'),
                    ('update', 'Actualizare'),
                    ('delete', 'Ștergere'),
                    ('status_change', 'Schimbare status'),
                    ('upload', 'Încărcare fișier'),
                    ('login', 'Autentificare'),
                    ('logout', 'Deconectare'),
                ],
                max_length=50,
                verbose_name='Acțiune',
            ),
        ),
    ]
