# Generated by Django 5.0.1 on 2026-02-05 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_username', models.CharField(max_length=150, verbose_name='Username actor')),
                ('action', models.CharField(choices=[('create', 'Creare'), ('update', 'Actualizare'), ('delete', 'Ștergere'), ('status_change', 'Schimbare status'), ('fraction_fulfilled', 'Fracție îndeplinită'), ('login', 'Autentificare'), ('logout', 'Deconectare')], max_length=20, verbose_name='Acțiune')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Tip entitate')),
                ('entity_id', models.CharField(max_length=100, verbose_name='ID entitate')),
                ('before_json', models.JSONField(blank=True, null=True, verbose_name='Stare înainte')),
                ('after_json', models.JSONField(blank=True, null=True, verbose_name='Stare după')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresă IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data și ora')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Jurnal audit',
                'verbose_name_plural': 'Jurnale audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
