# Generated by Django 5.0.1 on 2026-03-12 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0005_convictedperson_release_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicatie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titlu', models.CharField(max_length=255)),
                ('descriere', models.TextField(blank=True)),
                ('prioritate', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal'), ('SCAZUT', 'Scăzut')], default='NORMAL', max_length=20)),
                ('termen_limita', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatii_create', to=settings.AUTH_USER_MODEL)),
                ('persoana_legata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicatii', to='persons.convictedperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatieComentariu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatii_comentarii', to=settings.AUTH_USER_MODEL)),
                ('indicatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarii', to='indicatii.indicatie')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatieFisier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fisier', models.FileField(upload_to='indicatii/')),
                ('nume_fisier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fisiere', to='indicatii.indicatie')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatii_fisiere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatieDestinatari',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOU', 'Nou'), ('IN_LUCRU', 'În lucru'), ('INDEPLINIT', 'Îndeplinit')], default='NOU', max_length=20)),
                ('data_indeplinire', models.DateTimeField(blank=True, null=True)),
                ('destinatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicatii_primite', to=settings.AUTH_USER_MODEL)),
                ('indicatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatari', to='indicatii.indicatie')),
            ],
            options={
                'ordering': ['destinatar__first_name'],
                'unique_together': {('indicatie', 'destinatar')},
            },
        ),
    ]
