# Generated by Django 5.0.1 on 2026-03-12 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatii', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SablonIndicatie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(help_text='Numele șablonului', max_length=255)),
                ('titlu', models.CharField(help_text='Titlul indicației generate', max_length=255)),
                ('descriere', models.TextField(blank=True)),
                ('prioritate', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal'), ('SCAZUT', 'Scăzut')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabloane_create', to=settings.AUTH_USER_MODEL)),
                ('destinatari_default', models.ManyToManyField(blank=True, related_name='sabloane_indicatii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nume'],
            },
        ),
    ]
