# Generated by Django 5.0.1 on 2026-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatii', '0002_sablonindicatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatie',
            name='instanta',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sablonindicatie',
            name='instanta',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
