# Generated by Django 5.0.1 on 2026-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatii', '0003_add_instanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatie',
            name='data_hotarire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatie',
            name='tip_hotarire',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sablonindicatie',
            name='data_hotarire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sablonindicatie',
            name='tip_hotarire',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
