# Generated by Django 5.0.1 on 2026-02-05 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('sentences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('imminent', 'Iminent (≤30 zile)'), ('upcoming', 'În curând (30-90 zile)'), ('overdue', 'Depășit'), ('fulfilled', 'Îndeplinit')], max_length=20, verbose_name='Tip alertă')),
                ('priority', models.CharField(choices=[('high', 'Ridicată'), ('medium', 'Medie'), ('low', 'Scăzută')], default='medium', max_length=10, verbose_name='Prioritate')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('target_date', models.DateField(verbose_name='Data țintă')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citită')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('fraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sentences.fraction', verbose_name='Fracție')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='persons.convictedperson', verbose_name='Persoană')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Alertă',
                'verbose_name_plural': 'Alerte',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='alerts_aler_user_id_d01ece_idx'), models.Index(fields=['alert_type'], name='alerts_aler_alert_t_e287ad_idx'), models.Index(fields=['target_date'], name='alerts_aler_target__87786c_idx')],
            },
        ),
    ]
