# Generated by Django 5.0.1 on 2026-02-05 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crime_type', models.CharField(choices=[('furt', 'Furt'), ('furt_calificat', 'Furt calificat'), ('talharie', 'Tâlhărie'), ('omor', 'Omor'), ('omor_calificat', 'Omor calificat'), ('viol', 'Viol'), ('trafic_persoane', 'Trafic de persoane'), ('trafic_droguri', 'Trafic de droguri'), ('terorism', 'Terorism'), ('coruptie', 'Corupție'), ('evaziune', 'Evaziune fiscală'), ('inselaciune', 'Înșelăciune'), ('distrugere', 'Distrugere'), ('ultraj', 'Ultraj'), ('lovire', 'Lovire sau alte violențe'), ('vatamare', 'Vătămare corporală'), ('altul', 'Altul')], max_length=30, verbose_name='Tip infracțiune')),
                ('crime_description', models.TextField(blank=True, verbose_name='Descriere infracțiune')),
                ('sentence_years', models.PositiveSmallIntegerField(default=0, verbose_name='Ani')),
                ('sentence_months', models.PositiveSmallIntegerField(default=0, verbose_name='Luni')),
                ('sentence_days', models.PositiveSmallIntegerField(default=0, verbose_name='Zile')),
                ('start_date', models.DateField(verbose_name='Data începerii executării')),
                ('status', models.CharField(choices=[('active', 'Activă'), ('suspended', 'Suspendată'), ('completed', 'Finalizată'), ('conditionally_released', 'Liberare condiționată')], default='active', max_length=25, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sentences', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='persons.convictedperson', verbose_name='Persoană condamnată')),
            ],
            options={
                'verbose_name': 'Sentință',
                'verbose_name_plural': 'Sentințe',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fraction_type', models.CharField(choices=[('1/3', '1/3'), ('1/2', '1/2'), ('2/3', '2/3')], max_length=10, verbose_name='Tip fracție')),
                ('calculated_date', models.DateField(verbose_name='Data calculată')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Îndeplinit')),
                ('fulfilled_date', models.DateField(blank=True, null=True, verbose_name='Data îndeplinirii')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fractions', to='sentences.sentence', verbose_name='Sentință')),
            ],
            options={
                'verbose_name': 'Fracție',
                'verbose_name_plural': 'Fracții',
                'ordering': ['calculated_date'],
            },
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['status'], name='sentences_s_status_a611c7_idx'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['start_date'], name='sentences_s_start_d_d4546e_idx'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['crime_type'], name='sentences_s_crime_t_bfb54a_idx'),
        ),
        migrations.AddIndex(
            model_name='fraction',
            index=models.Index(fields=['calculated_date'], name='sentences_f_calcula_e67511_idx'),
        ),
        migrations.AddIndex(
            model_name='fraction',
            index=models.Index(fields=['is_fulfilled'], name='sentences_f_is_fulf_a0e479_idx'),
        ),
        migrations.AddIndex(
            model_name='fraction',
            index=models.Index(fields=['fraction_type'], name='sentences_f_fractio_a3027d_idx'),
        ),
    ]
