# Generated by Django 5.0.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_sentencereduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveArrest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Data început')),
                ('end_date', models.DateField(verbose_name='Data sfârșit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_preventive_arrests', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_arrests', to='sentences.sentence', verbose_name='Sentință')),
            ],
            options={
                'verbose_name': 'Arest preventiv',
                'verbose_name_plural': 'Arestări preventive',
                'ordering': ['start_date'],
            },
        ),
    ]
