# Generated by Django 5.0.1 on 2026-02-20 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Titlu')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('category', models.CharField(choices=[('BUG_CRITIC', 'Bug critic'), ('BUG_MINOR', 'Bug minor'), ('PROPUNERE', 'Propunere de îmbunătățire'), ('CERINTA_NOUA', 'Cerință nouă')], max_length=20, verbose_name='Categorie')),
                ('priority', models.CharField(choices=[('CRITIC', 'Critic'), ('INALT', 'Înalt'), ('MEDIU', 'Mediu'), ('SCAZUT', 'Scăzut')], default='MEDIU', max_length=20, verbose_name='Prioritate')),
                ('status', models.CharField(choices=[('NOU', 'Nou'), ('IN_LUCRU', 'În lucru'), ('TESTAT', 'Testat'), ('IMPLEMENTAT', 'Implementat'), ('RESPINS', 'Respins')], default='NOU', max_length=20, verbose_name='Status')),
                ('module_name', models.CharField(blank=True, help_text='Numele modulului/componentei SIA afectate', max_length=200, verbose_name='Modulul afectat')),
                ('steps_to_reproduce', models.TextField(blank=True, verbose_name='Pași de reproducere')),
                ('expected_behavior', models.TextField(blank=True, verbose_name='Comportament așteptat')),
                ('actual_behavior', models.TextField(blank=True, verbose_name='Comportament actual')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Note rezolvare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_issues', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
            ],
            options={
                'verbose_name': 'Problemă',
                'verbose_name_plural': 'Probleme',
                'ordering': ['-created_at'],
            },
        ),
    ]
